@startuml
autonumber 1
title Refresh User ID
actor User

User->App: start
App->App: getStoredUserId()
App->Server: refreshUserId(userId)
Server->Server: isUserIdStillValid(userId)

alt user id invalid
  Server->Server: generateAndStoreNewUserId()
else user id valid
  Server->Server: reuse same user id
end

App<--Server: userId

@enduml
