name: Android CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  cancel:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }} 

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      working-directory: ./app
      run: ./gradlew -q clean assembleRelease
    - name: Archive Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: app/app/build/outputs/apk/release/apk-release.apk
        retention-days: 10   

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Test
      working-directory: ./app
      run: ./gradlew -q testDebug
    - name: Archive Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: testDebug-report
        path: app/app/build/reports/tests/testDebugUnitTest
        retention-days: 10
