name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build
      working-directory: ./app
      run: ./gradlew -q clean assembleRelease
    - name: Test
      working-directory: ./app
      run: ./gradlew -q testDebug
    - name: Archive APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: app/app/build/outputs/apk/release/apk-release-unsigned.apk
        retention-days: 10   
    - name: Archive Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with: 
        name: testDebug-report
        path: app/app/build/reports/tests/testDebugUnitTest
        retention-days: 10
